<script>
export default {
    onLaunch: function() {
        console.log('App Launch');
        plus.screen.lockOrientation('portrait-primary'); //锁定
    },
    onShow: function() {
        console.log('App Show');
    },
    onHide: function() {
        console.log('App Hide');
    }
};
</script>

<style lang="less">
/*每个页面公共css */
/* This stylesheet generated by Transfonter (https://transfonter.org) on April 16, 2018 10:16 AM */
@import './style/global.less';
@import './style/variable.less';
@import './style/iconfont.css';
</style>
